const PHOTOS_COUNT = 25;

const MIN_COMMENTS_PER_PHOTO = 1;
const MAX_COMMENTS_PER_PHOTO = 15;
const MAX_COMMENTS_COUNT = 1000;
const DISPLAY_COMMENTS_STEP = 5;
const AVATAR_COUNT = 6;

export {
  PHOTOS_COUNT,
  MIN_COMMENTS_PER_PHOTO,
  MAX_COMMENTS_PER_PHOTO,
  MAX_COMMENTS_COUNT,
  DISPLAY_COMMENTS_STEP,
  AVATAR_COUNT
};
